name: Check IMAX Movies

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-movies:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent hung jobs

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver selenium

    - name: Run movie checker
      run: |
        google-chrome --version  # Print Chrome version for debugging
        python check-movies-json.py

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add movies.json scraper.log
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update movies.json [skip ci]"
          git push
        fi
