name: Scrape IMAX Movies

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python check-movies-json.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add movies.json
          git commit -m "Update movies.json" || exit 0
          git push
