name: Update Movies Data

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run movie checker
      run: python check-movies-json.py

    - name: Commit and push if changed
      run: |
        git config --local user.email github-actions[bot]@users.noreply.github.com
        git config --local user.name github-actions[bot]
        git add movies.json
        git commit -m Update movies data || exit 0
        git push

