name: Update Movies Data

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:

permissions:
  contents: write  # Add this to ensure the action can push changes

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.x'

    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase

    - name: Run movie checker
      run: |
        python check-movies-json.py

    - name: Debug file status
      run: |
        ls -la movies.json
        cat movies.json

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add movies.json
        git diff --staged --quiet || (git commit -m "Update movies data [skip ci]" && git push)
