name: Update Movies Data

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        chrome --version
        chromedriver --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Add wait time before script
      run: |
        sleep 10  # Add a 10 second wait before running the script

    - name: Run movie checker with retry
      run: |
        for i in {1..3}; do
          python check-movies-json.py && break || {
            if [[ $i == 3 ]]; then
              echo "Failed after 3 attempts"
              exit 1
            fi
            echo "Attempt $i failed! Waiting 30 seconds..."
            sleep 30
          }
        done

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add movies.json
        git commit -m "Update movies data" || exit 0
        git push

    - name: Upload error logs if failed
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          movies.json
